server:
  port: 8888
spring:
  application:
    name: 04-rdg-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rdGxd/rdg-config-server
          default-label: main
          search-paths:
            - 'greeting-service*'